env = Environment(
    CPPPATH = ['../KPHP', '../common'],
    CXXFLAGS = ['-std=gnu++17', '-fcommon'],
)
env.Command('kphp', 'main.php', '../kphp2cpp -f ../KPHP/functions.txt -d . main.php')
env.Program('main', Glob('kphp/*.cpp', exclude = 'kphp/xmain.cpp'), LIBS = ['kphp-engine', 're2', 'pcre', 'z', 'crypto'], LIBPATH = '..')
