name: Release KDB

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: sudo apt install -y libre2-dev libpcre2-dev libssl-dev zlib1g-dev libgraphicsmagick1-dev libwebp-dev scons
    - name: Build
      run: scons -j$(nproc --all)
    - name: Bundle KPHP SDK
      run: zip -r9 kphp-sdk.zip KPHP/*.h KPHP/runtime/*.h KPHP/runtime/array.cpp KPHP/runtime/class.cpp KPHP/runtime/variable.cpp KPHP/runtime/string.cpp KPHP/runtime/string_buffer.cpp common/fast-backtrace.h libkphp-runtime.a libkphp-engine.a kphp2cpp
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        name: KDB alpha ${{ github.sha }}
        tag_name: nightly
        make_latest: true
        prerelease: true
        files: |
          *-engine
          *.so
          *.a
          kphp2cpp
          kphp-sdk.zip
