name: Release KDB

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: sudo apt install -y libre2-dev libpcre-dev libssl-dev zlib1g-dev
    - name: Create TL constants
      run: mkdir -p objs/TL objs/bin && make objs/TL/constants.h
    - name: Build
      run: ./ezfile.c
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        name: KDB alpha ${{ github.sha }}
        prerelease: true
        files: |
          out/*-engine
          out/lib*.so
          out/lib*.a
          kphp-engine.o
          kphp2cpp
